export const keycodes = {
  // Based on Adafruit HID keycode.py https://github.com/adafruit/Adafruit_CircuitPython_HID/blob/main/adafruit_hid/keycode.py
  keyboard: [
    { label: 'A', value: 'A' },
    { label: 'B', value: 'B' },
    { label: 'C', value: 'C' },
    { label: 'D', value: 'D' },
    { label: 'E', value: 'E' },
    { label: 'F', value: 'F' },
    { label: 'G', value: 'G' },
    { label: 'H', value: 'H' },
    { label: 'I', value: 'I' },
    { label: 'J', value: 'J' },
    { label: 'K', value: 'K' },
    { label: 'L', value: 'L' },
    { label: 'M', value: 'M' },
    { label: 'N', value: 'N' },
    { label: 'O', value: 'O' },
    { label: 'P', value: 'P' },
    { label: 'Q', value: 'Q' },
    { label: 'R', value: 'R' },
    { label: 'S', value: 'S' },
    { label: 'T', value: 'T' },
    { label: 'U', value: 'U' },
    { label: 'V', value: 'V' },
    { label: 'W', value: 'W' },
    { label: 'X', value: 'X' },
    { label: 'Y', value: 'Y' },
    { label: 'Z', value: 'Z' },

    { label: '1', value: 'ONE' },
    { label: '2', value: 'TWO' },
    { label: '3', value: 'THREE' },
    { label: '4', value: 'FOUR' },
    { label: '5', value: 'FIVE' },
    { label: '6', value: 'SIX' },
    { label: '7', value: 'SEVEN' },
    { label: '8', value: 'EIGHT' },
    { label: '9', value: 'NINE' },
    { label: '0', value: 'ZERO' },

    { label: 'Enter', value: 'ENTER' },
    { label: 'Esc', value: 'ESCAPE' },
    { label: 'Backspace', value: 'BACKSPACE' },
    { label: 'Tab', value: 'TAB' },
    { label: 'Space', value: 'SPACEBAR' },
    { label: 'Minus', value: 'MINUS' },
    { label: 'Equals', value: 'EQUALS' },
    { label: 'Left Bracket', value: 'LEFT_BRACKET' },
    { label: 'Right Bracket', value: 'RIGHT_BRACKET' },
    { label: 'Backslash', value: 'BACKSLASH' },
    { label: 'Pound', value: 'POUND' },
    { label: 'Semicolon', value: 'SEMICOLON' },
    { label: 'Quote', value: 'QUOTE' },
    { label: 'Grave Accent', value: 'GRAVE_ACCENT' },
    { label: 'Comma', value: 'COMMA' },
    { label: 'Period', value: 'PERIOD' },
    { label: 'Forward Slash', value: 'FORWARD_SLASH' },
    { label: 'Caps Lock', value: 'CAPS_LOCK' },

    { label: 'F1', value: 'F1' },
    { label: 'F2', value: 'F2' },
    { label: 'F3', value: 'F3' },
    { label: 'F4', value: 'F4' },
    { label: 'F5', value: 'F5' },
    { label: 'F6', value: 'F6' },
    { label: 'F7', value: 'F7' },
    { label: 'F8', value: 'F8' },
    { label: 'F9', value: 'F9' },
    { label: 'F10', value: 'F10' },
    { label: 'F11', value: 'F11' },
    { label: 'F12', value: 'F12' },

    { label: 'Up', value: 'UP_ARROW' },
    { label: 'Down', value: 'DOWN_ARROW' },
    { label: 'Left', value: 'LEFT_ARROW' },
    { label: 'Right', value: 'RIGHT_ARROW' },

    { label: 'Insert', value: 'INSERT' },
    { label: 'Home', value: 'HOME' },
    { label: 'Page Up', value: 'PAGE_UP' },
    { label: 'Page Down', value: 'PAGE_DOWN' },
    { label: 'Delete', value: 'DELETE' },
    { label: 'End', value: 'END' },

    { label: 'Print Screen', value: 'PRINT_SCREEN' },
    { label: 'Scroll Lock', value: 'SCROLL_LOCK' },
    { label: 'Pause', value: 'PAUSE' },

    { label: 'Numpad Lock', value: 'KEYPAD_NUMLOCK' },
    { label: 'Numpad Slash', value: 'KEYPAD_FORWARD_SLASH' },
    { label: 'Numpad Asterisk', value: 'KEYPAD_ASTERISK' },
    { label: 'Numpad Minus', value: 'KEYPAD_MINUS' },
    { label: 'Numpad Plus', value: 'KEYPAD_PLUS' },
    { label: 'Numpad Enter', value: 'KEYPAD_ENTER' },
    { label: 'Numpad 1', value: 'KEYPAD_ONE' },
    { label: 'Numpad 2', value: 'KEYPAD_TWO' },
    { label: 'Numpad 3', value: 'KEYPAD_THREE' },
    { label: 'Numpad 4', value: 'KEYPAD_FOUR' },
    { label: 'Numpad 5', value: 'KEYPAD_FIVE' },
    { label: 'Numpad 6', value: 'KEYPAD_SIX' },
    { label: 'Numpad 7', value: 'KEYPAD_SEVEN' },
    { label: 'Numpad 8', value: 'KEYPAD_EIGHT' },
    { label: 'Numpad 9', value: 'KEYPAD_NINE' },
    { label: 'Numpad 0', value: 'KEYPAD_ZERO' },
    { label: 'Numpad Period', value: 'KEYPAD_PERIOD' },
    { label: 'Numpad Backslash', value: 'KEYPAD_BACKSLASH' },

    { label: 'Control', value: 'LEFT_CONTROL' },
    { label: 'Shift', value: 'LEFT_SHIFT' },
    { label: 'Alt/Option', value: 'ALT' },
    { label: 'Win/Command', value: 'GUI' },
    { label: 'Right Control', value: 'RIGHT_CONTROL' },
    { label: 'Right Shift', value: 'RIGHT_SHIFT' },
    { label: 'Right Alt', value: 'RIGHT_ALT' },
    { label: 'Right Win/Command', value: 'RIGHT_GUI' },
  ],

  mouse_button: [
    { label: 'Left Click', value: 'LEFT_BUTTON' },
    { label: 'Right Click', value: 'RIGHT_BUTTON' },
    { label: 'Middle Click', value: 'MIDDLE_BUTTON' },
  ],

  mouse_move: [
    { label: 'X-axis', value: 'X' },
    { label: 'Y-axis', value: 'Y' },
    { label: 'Scroll Wheel', value: 'WHEEL' },
  ],
  analog: [
    { label: 'Left Stick X', value: 'LSX' },
    { label: 'Left Stick Y', value: 'LSY' },
    { label: 'Right Stick X', value: 'RSX' },
    { label: 'Right Stick Y', value: 'RSY' },
    { label: 'Left Trigger', value: 'LT' },
    { label: 'Right Trigger', value: 'RT' },
  ],
  gamepad: [
    { label: 'A', value: 'A' },
    { label: 'B', value: 'B' },
    { label: 'X', value: 'X' },
    { label: 'Y', value: 'Y' },
    { label: 'Left Bumper', value: 'LB' },
    { label: 'Right Bumper', value: 'RB' },
    { label: 'Back', value: 'BACK' },
    { label: 'Start', value: 'START' },
    { label: 'Left Stick Button', value: 'LSB' },
    { label: 'Right Stick Button', value: 'RSB' },
    { label: 'D-Pad Up', value: 'UP' },
    { label: 'D-Pad Down', value: 'DOWN' },
    { label: 'D-Pad Left', value: 'LEFT' },
    { label: 'D-Pad Right', value: 'RIGHT' },
    { label: 'Home', value: 'HOME' },
    { label: 'Share', value: 'SHARE' },
  ],

  macro: [],
}
